name: First Pipeline

on:
  push:
    branches:
      - main

jobs:
  my-first-job:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show File Content
        run: cat app.txt
